config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'urls#index'  # See how all your routes lay out with "rake routes".

  resources :urls
  resources :dashboard, only: [:show]
  get "/:shortcut", to: "urls#show"

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :user

  validates :target, :length => { minimum:5 }, :format => URI::regexp(%w(http https)), :presence => true
  after_create :create_shortcut

  def create_shortcut
    update_attribute(:shortcut, self.id.to_s(36))
  end

end
  

app/models/user.rb
class User < ActiveRecord::Base
  has_many :urls
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @my_urls = my_urls
  end

  def my_urls
    if user_signed_in?
      @my_urls = Url.where('user_id = ?', current_user.id)
    end
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
  end

  def show
    @url = Url.find_by_shortcut!(params[:shortcut])
    redirect_to @url.target
  end
  
  def new
    @url = Url.new
  end

  def create
    @url = current_user.urls.create(url_params)
    if @url.valid?
      @url.save
      redirect_to dashboard_path(current_user)
    else 
      flash[:notice] = "Please use http:// or https://"
      render :new, :status => :unprocessable_entity
    end
  end

  def destroy
    @url = Url.find(params[:id])
    if @url.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
    @url.destroy
    redirect_to dashboard_path(current_user)
  end

  private

  def url_params
    params.require(:url).permit(:target)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/dashboard/show.html.erb
<div class = "col-xs-10 col-xs-offset-2">
  <table>
    <caption><center><h3>My URLs</h3></center></caption>
      <tr>
          <td><b>Target URL</b></td>
          <td><b>Shortcut</b></td>
          <td><b>Delete</b></td>
      </tr>
    <% if @my_urls.present? %>
      <% @my_urls.each do |my_url| %>
          <tr>
            <td><%= my_url.target %></td>
            <td><a href = "<%= my_url.target %>"><%= "crunch-url.herokuapp.com/#{my_url.shortcut}"%></a></td>
            <td><%= link_to "DELETE", url_path(my_url), :method => :delete, :data =>{ :confirm => 'Are You Sure You Want To Delete This?'}, :class => 'btn btn-danger' %> </td>
          </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrunchUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'CRUNCH-URL', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
      <!-- Button Trigger -->
          <% if user_signed_in? %>
            <li><%= link_to 'NEW URL', '#', :data => {:toggle => 'modal', :target => '#myModal'} %></li>
          <% end %>
        </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'DASHBOARD', dashboard_path(current_user) %></li>
          <li><%= link_to 'SIGN OUT', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
          <li><%= link_to 'SIGN IN', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Shorten URL</h4>
        </div>
        <%= simple_form_for Url.new do |f| %>
        <div class="modal-body">
          <%= f.input :target,  :label => "Enter URL" %>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Shorten', :class => 'btn btn-danger' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>


<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<div class = "white-box col-xs-10 col-xs-offset-1">
  <center>
    <h1> Welcome To Crunch-URL </h1>
    <h3>sign up to start crunching urls!</h3>
  </center>
</div>  

app/views/urls/new.html.erb
<div class="shadow-box col-xs-10 col-xs-offset-1">
  <h1>Shorten Your URL</h1>
  <%= simple_form_for @url do |f| %>
    <%= f.input :target, :label => "Enter URL" %>
    <br />
    <%= f.submit 'Shorten', class: 'btn btn-danger' %>
  <% end %>
</div>